@startuml
digraph G {
	1 -> 7 [label = 14]
	2 -> 6 [label = 46]
	2 -> 9 [label = 14]
	2 -> 2 [label = 29]
	2 -> 3 [label = 97]
	2 -> 5 [label = 98]
	4 -> 2 [label = 47]
	4 -> 6 [label = 64]
	4 -> 5 [label = 91]
	5 -> 9 [label = 84]
	5 -> 7 [label = 48]
	6 -> 4 [label = 57]
	6 -> 2 [label = 95]
	7 -> 2 [label = 46]
	7 -> 7 [label = 90]
	7 -> 5 [label = 66]
	7 -> 6 [label = 46]
	7 -> 3 [label = 11]
	8 -> 9 [label = 93]
	8 -> 4 [label = 7]
	9 -> 3 [label = 54]
	10 -> 3 [label = 81]
}
@enduml
