@startuml
digraph G {
	1 -> 7 [label = 61]
	2 -> 1 [label = 56]
	2 -> 2 [label = 34]
	2 -> 5 [label = 44]
	3 -> 8 [label = 34]
	4 -> 9 [label = 34]
	5 -> 5 [label = 18]
	5 -> 8 [label = 54]
	6 -> 5 [label = 3]
	6 -> 1 [label = 89]
	7 -> 6 [label = 99]
	7 -> 8 [label = 19]
	8 -> 6 [label = 63]
	8 -> 1 [label = 8]
	8 -> 2 [label = 48]
	8 -> 7 [label = 25]
	8 -> 9 [label = 38]
	9 -> 10 [label = 96]
	10 -> 5 [label = 31]
}
@enduml
