@startuml
digraph G {
	1 -> 4 [label = 37]
	1 -> 1 [label = 97]
	2 -> 8 [label = 57]
	3 -> 10 [label = 95]
	3 -> 6 [label = 73]
	3 -> 9 [label = 99]
	3 -> 3 [label = 70]
	4 -> 4 [label = 92]
	5 -> 8 [label = 2]
	5 -> 5 [label = 20]
	6 -> 2 [label = 15]
	7 -> 2 [label = 17]
	7 -> 7 [label = 19]
	8 -> 5 [label = 21]
	8 -> 6 [label = 43]
	9 -> 10 [label = 15]
	9 -> 6 [label = 46]
	9 -> 1 [label = 38]
	9 -> 4 [label = 60]
	10 -> 9 [label = 28]
	10 -> 7 [label = 69]
}
@enduml
