@startuml
digraph G {
	2 -> 4 [label = 20]
	2 -> 3 [label = 71]
	5 -> 1 [label = 6]
	5 -> 5 [label = 57]
	6 -> 2 [label = 48]
	6 -> 10 [label = 8]
	6 -> 6 [label = 46]
	8 -> 7 [label = 65]
	10 -> 8 [label = 29]
	10 -> 9 [label = 90]
}
@enduml
