@startuml
digraph G {
	1 -> 6 [label = 80]
	2 -> 4 [label = 42]
	3 -> 3 [label = 24]
	4 -> 5 [label = 79]
	4 -> 6 [label = 64]
	4 -> 3 [label = 8]
	5 -> 10 [label = 82]
	5 -> 4 [label = 19]
	5 -> 5 [label = 20]
	5 -> 8 [label = 99]
	5 -> 6 [label = 37]
	6 -> 10 [label = 48]
	6 -> 4 [label = 24]
	6 -> 2 [label = 75]
	7 -> 3 [label = 19]
	7 -> 6 [label = 81]
	7 -> 10 [label = 93]
	7 -> 4 [label = 16]
	7 -> 5 [label = 2]
	8 -> 7 [label = 3]
	8 -> 2 [label = 81]
	8 -> 9 [label = 29]
	8 -> 6 [label = 18]
	8 -> 3 [label = 66]
	8 -> 4 [label = 96]
	8 -> 1 [label = 97]
	9 -> 7 [label = 35]
	9 -> 6 [label = 87]
	9 -> 4 [label = 76]
	9 -> 2 [label = 68]
	9 -> 8 [label = 58]
	10 -> 9 [label = 9]
	10 -> 8 [label = 43]
	10 -> 10 [label = 81]
	10 -> 2 [label = 74]
	10 -> 7 [label = 21]
}
@enduml
