@startuml
digraph G {
	1 -> 2 [label = 42]
	2 -> 3 [label = 81]
	3 -> 8 [label = 12]
	4 -> 10 [label = 86]
	5 -> 7 [label = 6]
	6 -> 8 [label = 51]
	7 -> 8 [label = 58]
	8 -> 5 [label = 29]
	8 -> 7 [label = 19]
	9 -> 8 [label = 77]
	9 -> 10 [label = 85]
	9 -> 9 [label = 20]
	10 -> 4 [label = 81]
}
@enduml
