@startuml
digraph G {
	1 -> 18 [label = 10]
	1 -> 14 [label = 62]
	2 -> 5 [label = 45]
	2 -> 3 [label = 77]
	2 -> 16 [label = 11]
	2 -> 15 [label = 12]
	2 -> 7 [label = 72]
	2 -> 17 [label = 15]
	2 -> 8 [label = 36]
	3 -> 13 [label = 79]
	3 -> 9 [label = 4]
	3 -> 6 [label = 94]
	3 -> 2 [label = 90]
	4 -> 3 [label = 36]
	4 -> 15 [label = 90]
	4 -> 6 [label = 9]
	4 -> 8 [label = 5]
	4 -> 12 [label = 12]
	5 -> 12 [label = 9]
	5 -> 14 [label = 37]
	5 -> 13 [label = 13]
	5 -> 18 [label = 97]
	5 -> 8 [label = 86]
	5 -> 9 [label = 10]
	6 -> 17 [label = 92]
	6 -> 9 [label = 76]
	6 -> 7 [label = 95]
	7 -> 9 [label = 24]
	7 -> 13 [label = 7]
	7 -> 20 [label = 58]
	7 -> 8 [label = 99]
	8 -> 9 [label = 97]
	8 -> 3 [label = 7]
	8 -> 7 [label = 48]
	8 -> 11 [label = 60]
	9 -> 7 [label = 43]
	9 -> 8 [label = 33]
	9 -> 6 [label = 47]
	9 -> 1 [label = 45]
	10 -> 2 [label = 57]
	10 -> 4 [label = 91]
	10 -> 5 [label = 46]
	10 -> 18 [label = 9]
	10 -> 8 [label = 58]
	11 -> 14 [label = 39]
	11 -> 7 [label = 97]
	11 -> 17 [label = 30]
	11 -> 13 [label = 87]
	11 -> 12 [label = 53]
	11 -> 8 [label = 57]
	11 -> 9 [label = 98]
	12 -> 4 [label = 82]
	12 -> 11 [label = 41]
	12 -> 15 [label = 95]
	13 -> 7 [label = 85]
	13 -> 16 [label = 69]
	13 -> 15 [label = 21]
	13 -> 5 [label = 62]
	13 -> 18 [label = 20]
	14 -> 19 [label = 25]
	14 -> 10 [label = 71]
	15 -> 8 [label = 92]
	15 -> 17 [label = 0]
	15 -> 5 [label = 47]
	15 -> 7 [label = 43]
	15 -> 19 [label = 96]
	15 -> 2 [label = 16]
	16 -> 18 [label = 7]
	16 -> 19 [label = 27]
	16 -> 4 [label = 8]
	16 -> 7 [label = 59]
	16 -> 15 [label = 28]
	16 -> 6 [label = 79]
	17 -> 13 [label = 42]
	17 -> 14 [label = 34]
	17 -> 12 [label = 77]
	17 -> 4 [label = 8]
	18 -> 3 [label = 96]
	18 -> 19 [label = 44]
	19 -> 2 [label = 65]
	19 -> 17 [label = 10]
	19 -> 5 [label = 56]
	20 -> 14 [label = 40]
}
@enduml
